database_engines = {
    'MySQL': 'mysql+pymysql',
    'PostgreSQL': 'postgresql+psycopg2',
    'SQLite': 'sqlite',
    'Oracle': 'oracle+cx_oracle',
    'Microsoft SQL Server': 'mssql+pymssql',
    'Firebird': 'firebird',
    'Sybase': 'sybase',
    'Informix': 'informix',
    'Microsoft Access': 'access',
    'IBM DB2': 'ibm_db_sa',
    'Drizzle': 'drizzle',
    'SQL Anywhere': 'sqlany',
    'SAP HANA': 'hana',
    'MaxDB': 'maxdb',
    'SAP DB': 'sapdb',
    'HSQLDB': 'hsqldb',
    'SQLCipher': 'sqlcipher',
    'Teradata': 'teradata',
    'Presto': 'presto',
    'Snowflake': 'snowflake',
    'Amazon Redshift': 'redshift',
    'CockroachDB': 'cockroachdb',
    'MonetDB': 'monetdb',
    'Vertica': 'vertica',
    'Cubrid': 'cubrid',
    'Crate': 'crate',
    'Altibase': 'altibase',
    'OmniSci': 'omnisci',
    'ClickHouse': 'clickhouse',
    'MongoDB': 'mongo',
    'Amazon DocumentDB': 'documentdb',
    'DynamoDB': 'dynamodb',
    'Google Cloud Spanner': 'google',
    'Amazon Timestream': 'timestream',
    'Trino': 'trino',
    'Google BigQuery': 'bigquery',
    'MariaDB': 'mysql',
    'Exasol': 'exasol',
    'Netezza': 'netezza',
    'Greenplum': 'greenplum',
    'Kdb+': 'kdb+',
    'Solr': 'solr',
    'Nexus': 'nexus',
    'Cassandra': 'cassandra',
    'OpenTSDB': 'opentsdb',
    'Azure Cosmos DB': 'cosmosdb',
    'Google Bigtable': 'bigtable',
    'Apache HBase': 'hbase',
    'Apache Accumulo': 'accumulo',
    'MemSQL': 'memsql',
    'Amazon Athena': 'athena',
    'Amazon S3': 's3',
    'AWS Glue': 'glue',
    'Elasticsearch': 'elasticsearch',
    'Azure Data Explorer (Kusto)': 'kusto',
    'Google Firebase': 'firebase',
    'Microsoft Azure Cosmos DB': 'cosmosdb',
    'Apache Hadoop HDFS': 'hdfs',
    'Microsoft Azure Data Lake Storage': 'adl',
    'Apache Phoenix': 'phoenix',
    'Apache Ignite': 'ignite',
    'Apache Geode': 'geode',
    'GridGain': 'gridgain',
    'Google Firestore': 'firestore',
    'MongoDB Atlas': 'atlas',
    'Google Cloud Datastore': 'datastore'
}

database_engines_jdbc = {
    'MySQL': 'mysql+pymysql',
    'PostgreSQL': 'postgresql',
    'SQLite': 'sqlite',
    'Oracle': 'oracle+cx_oracle',
    'Microsoft SQL Server': 'mssql+pymssql',
    'Firebird': 'firebird',
    'Sybase': 'sybase',
    'Informix': 'informix',
    'Microsoft Access': 'access',
    'IBM DB2': 'ibm_db_sa',
    'Drizzle': 'drizzle',
    'SQL Anywhere': 'sqlany',
    'SAP HANA': 'hana',
    'MaxDB': 'maxdb',
    'SAP DB': 'sapdb',
    'HSQLDB': 'hsqldb',
    'SQLCipher': 'sqlcipher',
    'Teradata': 'teradata',
    'Presto': 'presto',
    'Snowflake': 'snowflake',
    'Amazon Redshift': 'redshift',
    'CockroachDB': 'cockroachdb',
    'MonetDB': 'monetdb',
    'Vertica': 'vertica',
    'Cubrid': 'cubrid',
    'Crate': 'crate',
    'Altibase': 'altibase',
    'OmniSci': 'omnisci',
    'ClickHouse': 'clickhouse',
    'MongoDB': 'mongo',
    'Amazon DocumentDB': 'documentdb',
    'DynamoDB': 'dynamodb',
    'Google Cloud Spanner': 'google',
    'Amazon Timestream': 'timestream',
    'Trino': 'trino',
    'Google BigQuery': 'bigquery',
    'MariaDB': 'mysql',
    'Exasol': 'exasol',
    'Netezza': 'netezza',
    'Greenplum': 'greenplum',
    'Kdb+': 'kdb+',
    'Solr': 'solr',
    'Nexus': 'nexus',
    'Cassandra': 'cassandra',
    'OpenTSDB': 'opentsdb',
    'Azure Cosmos DB': 'cosmosdb',
    'Google Bigtable': 'bigtable',
    'Apache HBase': 'hbase',
    'Apache Accumulo': 'accumulo',
    'MemSQL': 'memsql',
    'Amazon Athena': 'athena',
    'Amazon S3': 's3',
    'AWS Glue': 'glue',
    'Elasticsearch': 'elasticsearch',
    'Azure Data Explorer (Kusto)': 'kusto',
    'Google Firebase': 'firebase',
    'Microsoft Azure Cosmos DB': 'cosmosdb',
    'Apache Hadoop HDFS': 'hdfs',
    'Microsoft Azure Data Lake Storage': 'adl',
    'Apache Phoenix': 'phoenix',
    'Apache Ignite': 'ignite',
    'Apache Geode': 'geode',
    'GridGain': 'gridgain',
    'Google Firestore': 'firestore',
    'MongoDB Atlas': 'atlas',
    'Google Cloud Datastore': 'datastore'
}
